VIRUSTOTAL_API_KEY: 5df8d97dd0dc875d1caa23c90ad77f4c6382094c94449f0b3dec654c0b8d44a4

GEOIP_WHITELIST_ZONES: ['US', 'IN']

GEOIP_REDLIST_ZONES: ['CN', 'CHN', 'RU', 'KP']

PRIVATE_IP: ["10", "172", "192", "127"]